#!/usr/bin/env zsh

if [[ -n $JUST_WANT_PATH ]] ; then
    return
fi

HISTFILE=~/.histfile
HISTSIZE=100000
SAVEHIST=100000
setopt extendedglob notify
unsetopt nomatch
bindkey -e

# Controls which non-letters *are* considered words for jumping (opt+b, opt+f, etc)
WORDCHARS='-_'

# COMPINSTALL
zstyle :compinstall filename '/Users/bwm/.zshrc'

if (( $+commands[brew] )) ; then
    # technically this should be BREW_PREFIX=$(brew --prefix) but that starts a ruby
    # interpreter, which sucks for shell startup time.
    for brew_prefix in /usr/local /opt/homebrew /home/linuxbrew/.linuxbrew ; do
        if [[ -d ${brew_prefix}/share/zsh/site-functions ]] ; then
            fpath+=(${brew_prefix}/share/zsh/site-functions)
            break
        fi
    done
fi

fpath=($fpath $HOME/.local/zsh-completions $HOME/.zplugin/completions)
zmodload -i zsh/complist
autoload -Uz compinit
autoload -U bashcompinit
# Skip the security check (compaudit) and reuse the existing dump if it was
# regenerated within the last 24h. Saves ~200ms per shell startup.
if [[ -n ${ZDOTDIR:-$HOME}/.zcompdump(#qN.mh-24) ]]; then
  compinit -C
else
  compinit
fi
# End of lines added by compinstall

# Open current command line in vim
autoload edit-command-line
zle -N edit-command-line
bindkey "^X^E" edit-command-line

# autoload -U insert-last-word
# zle -N insert-last-word
# bindkey '^[.' insert-last-word

autoload -U copy-earlier-word
zle -N copy-earlier-word
bindkey '^[,' copy-earlier-word

### Added by Zinit's installer
# https://github.com/zdharma-continuum/zinit
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"
source "${ZINIT_HOME}/zinit.zsh"

autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
# zinit light-mode for \
#     zdharma-continuum/zinit-annex-as-monitor \
#     zdharma-continuum/zinit-annex-bin-gem-node \
#     zdharma-continuum/zinit-annex-patch-dl \
#     zdharma-continuum/zinit-annex-rust

### End of Zinit's installer chunk

# TAB COMPLETIONS
zinit ice wait"0b" lucid blockf
zinit light zsh-users/zsh-completions
zstyle ':completion:*' completer _expand _complete _ignored _approximate
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' menu select=2
zstyle ':completion:*' select-prompt '%SScrolling active: current selection at %p%s'
zstyle ':completion:*:descriptions' format '-- %d --'
zstyle ':completion:*:processes' command 'ps -au$USER'
zstyle ':completion:complete:*:options' sort false
zstyle ':completion:*:*:*:*:processes' command "ps -u $USER -o pid,user,comm,cmd -w -w"
zstyle ":completion:*:git-checkout:*" sort false
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}

#zstyle ':fzf-tab:complete:_zlua:*' query-string input
#zstyle ':fzf-tab:complete:kill:argument-rest' extra-opts --preview=$extract'ps --pid=$in[(w)1] -o cmd --no-headers -w -w' --preview-window=down:3:wrap

zinit ice wait lucid atload'_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

zinit ice wait lucid has"uv" id-as"uv-comp" as"null" \
  atload'eval "$(uv generate-shell-completion zsh)"'
zinit light zdharma-continuum/null

zinit ice wait lucid has"uvx" id-as"uvx-comp" as"null" \
  atload'eval "$(uvx --generate-shell-completion zsh)"'
zinit light zdharma-continuum/null

zinit ice wait lucid has"ruff" id-as"ruff-comp" as"null" \
  atload'eval "$(ruff generate-shell-completion zsh)"'
zinit light zdharma-continuum/null

# zsh-patina claims it is most reliable if it is the last thing sourced,
# so put it as the last atload
if (( $+commands[zsh-patina] )); then
  zinit ice wait lucid id-as"zsh-patina-hl" as"null" \
    atload'eval "$(zsh-patina activate)"'
  zinit light zdharma-continuum/null
else
  zinit ice wait lucid
  zinit light zdharma/fast-syntax-highlighting
fi


# inshellisense contradicts zsh-autosuggestions
#[ -f ~/.inshellisense/key-bindings.zsh ] && source ~/.inshellisense/key-bindings.zsh

zinit ice as"completion"
zinit snippet https://github.com/docker/cli/blob/master/contrib/completion/zsh/_docker

export FORGIT_CHECKOUT_BRANCH_BRANCH_GIT_OPTS='--sort=-committerdate'
[[ $UNAME == Linux && $TERM == wezterm ]] && export FORGIT_COPY_CMD="$COPY_COMMAND"
zinit ice wait lucid cp"bin/* -> $HOME/.local/bin/git-forgit"
zinit light wfxr/forgit

# zinit ice wait lucid
# zinit light Aloxaf/fzf-tab

# history
setopt incappendhistory       # write to history file after every command
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt share_history          # share command history data
# duplicate detection
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_all_dups   # Delete old recorded entry if new entry is a duplicate

######################################################################
# Extra commands

# Cache the output of `<tool> init`-style commands keyed by the tool binary's
# mtime. Saves several hundred ms of subprocess startup per shell.
__bwm_cached_eval() {
  local name="$1"; shift
  local bin_path="$1"; shift
  local cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/zsh-init"
  local cache_file="$cache_dir/$name.zsh"
  [[ -d $cache_dir ]] || mkdir -p "$cache_dir"
  if [[ ! -s $cache_file || $bin_path -nt $cache_file ]]; then
    "$@" > "$cache_file"
    zcompile -R -- "$cache_file" 2>/dev/null
  fi
  source "$cache_file"
}

if (( $+commands[mise] )); then
  __bwm_cached_eval mise-activate "$commands[mise]" mise activate zsh

  # mise's precmd/chpwd hooks spawn `mise hook-env` (~68ms) on every prompt and
  # cd. Wrap them so we only call mise when the set of config files (or their
  # mtimes) that would influence its output has actually changed.
  zmodload -F zsh/stat b:zstat
  typeset -g __bwm_mise_last_sig=""

  __bwm_mise_sig() {
    local dir="$PWD" name
    local -a t
    REPLY=""
    if zstat -A t +mtime -- "$HOME/.config/mise/config.toml" 2>/dev/null; then
      REPLY+="g:${t[1]};"
    fi
    while [[ $dir != / && -n $dir ]]; do
      for name in mise.toml .mise.toml mise.local.toml .mise.local.toml .tool-versions; do
        if zstat -A t +mtime -- "$dir/$name" 2>/dev/null; then
          REPLY+="$dir/$name:${t[1]};"
        fi
      done
      dir=${dir:h}
    done
  }

  _mise_hook_precmd() {
    if [[ "${__MISE_ZSH_CHPWD_RAN:-0}" == "1" ]]; then
      export __MISE_ZSH_CHPWD_RAN=0
      return
    fi
    __bwm_mise_sig
    [[ $REPLY == "$__bwm_mise_last_sig" ]] && return
    __bwm_mise_last_sig=$REPLY
    eval "$("$commands[mise]" hook-env -s zsh --reason precmd)"
  }

  _mise_hook_chpwd() {
    export __MISE_ZSH_CHPWD_RAN=1
    __bwm_mise_sig
    [[ $REPLY == "$__bwm_mise_last_sig" ]] && return
    __bwm_mise_last_sig=$REPLY
    eval "$("$commands[mise]" hook-env -s zsh --reason chpwd)"
  }

  # mise activate's tail already ran _mise_hook synchronously, so seed the
  # cached signature here to avoid one redundant call on the first prompt.
  __bwm_mise_sig
  __bwm_mise_last_sig=$REPLY
fi
zinit ice wait lucid has"zoxide" id-as"zoxide-init" as"null" \
  atload'eval "$(zoxide init --cmd j zsh)"'
zinit light zdharma-continuum/null

zinit ice wait lucid has"jj" id-as"jj-comp" as"null" \
  atload'source <(COMPLETE=zsh jj)'
zinit light zdharma-continuum/null

zinit ice wait lucid has"fzf" id-as"fzf-init" as"null" \
  atload'eval "$(fzf --zsh)"
  export FZF_DEFAULT_COMMAND=fd
  export FZF_CTRL_T_COMMAND=fd
  export FZF_ALT_C_COMMAND="fd --type directory"'
zinit light zdharma-continuum/null

# Prompt

if [[ -n "${WEZTERM_PANE}" ]]; then
  __BWM_LAST_GIT_ROOT=""
  # speedily catch git directory and set it up for wezterm
  typeset -A __BWM_GIT_DIRS

  bwm_gitroot() {
    local thisdir="${__BWM_GIT_DIRS[${PWD}]}"
    if [[ -n "$thisdir" && "$thisdir" != "<>" ]]; then
      printf "%s" "$thisdir"
      return
    elif [[ -n $thisdir ]]; then
      return
    fi
    local gitdir=$(git rev-parse --show-toplevel 2>/dev/null)
    if [[ -z "$gitdir" ]]; then
      __BWM_GIT_DIRS["$PWD"]="<>"
    else
      __BWM_GIT_DIRS["$PWD"]="$gitdir"
    fi
    printf "%s" "$gitdir"
  }

  __git_precmd() {
    local gr="$(bwm_gitroot)"
    if [[ $gr != $__BWM_LAST_GIT_ROOT ]]; then
      printf "\033]1337;SetUserVar=%s=%s\007" git_root "$(bwm_gitroot | base64)"
      __BWM_LAST_GIT_ROOT="$gr"
    fi
  }

  precmd_functions+=(__git_precmd)
fi

__check_mnt_cache() {
  [[ $USER != coder ]] && return
  if [[ -d /mnt/cache ]]; then
    unset MISSING_CACHE
  else
    export MISSING_CACHE="💥"
  fi
}
precmd_functions+=(__check_mnt_cache)

if (( $+commands[vcs-status-daemon] )); then
  __bwm_cached_eval vcs-status-daemon "$commands[vcs-status-daemon]" vcs-status-daemon init zsh
fi
if (( $+commands[starship] )); then
  __bwm_cached_eval starship "$commands[starship]" starship init zsh
fi

# End Prompt

if (( $+commands[nvim] )); then
    alias -r vim=nvim
    export EDITOR=nvim
else
    export EDITOR=vim
fi
alias -r aplay="ansible-playbook"
alias -r cm=chezmoi
alias -r dc="docker compose"
alias -r dsa='docker stop $(docker ps -q)' # docker stop all
alias -r e='emacsclient --no-wait --socket-name="${HOME}/.emacs.d/server/server"'
alias -r et='TERM=xterm-24bit COLORTERM=truecolor ALTERNATE_EDITOR="" emacsclient --tty --socket-name="${HOME}/.emacs.d/server/server"'
alias -r grep="grep --color=auto"
if (( $+commands[eza] )); then
  alias -r ls="eza --group-directories-first --sort extension"
  alias -r la="ls -lA --git"
  alias -r ll="ls -l --git"
else
  alias -r la="ls -lA"
  alias -r ll="ls -l"
fi
alias -r lzd='lazydocker'
alias -r lzg='lazygit'
alias -r ghprc='gh pr checkout'
alias -r tf=terraform
alias -r ubi="ubi --in $HOME/.local/bin"

# emacs magit
eg() {
    git_root=$(git rev-parse --show-toplevel)
    et -e "(progn (magit-status \"${git_root}\") (delete-other-windows))"
    if which osascript >/dev/null 2>&1; then
        osascript -e "tell application \"Emacs\" to activate"
    fi
}

# Set the the built-in time format to be more like bash, with some goodies.
export TIMEFMT='
real	%E
user	%U
sys	%S
%%cpu	%P
maxmem	%M KB
faults	%F'
export TIME="$TIMEFMT"

[[ -f $HOME/.wezterm.sh && $TERM == wezterm ]] && source "$HOME/.wezterm.sh"

REPO_DIR="$HOME/repos"

for f in ~/.config/zsh/*.zsh; do
    source "$f"
done

psgrep() {
    ps -eo 'pid ppid %cpu %mem etime args' \
      | rg --color=always "(PID|$1)" \
      | rg -v -w "rg" \
      | rg -o --color=never '^.{0,500}'
}

# github clone
ghc() {
    (
        cd "$REPO_DIR" || return 1
        git clone "$1"
    )
    local bn="${1##*/}"
    bn="${bn%%.*}"
    # show where it was cloned and put `cd $clonedir` in the clipboard
    echo
    echo "$REPO_DIR/${bn}" | tee >( echo -n "cd $(cat -)" | tr -d $'\n' | pbcopy)
}
ssm() {
    local fields="${GOSSM_FIELDS:-name,launch-time,id}"
    gossm start --region us-east-2 --fields "$fields" "$@"
}
aws_token() {
    unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN
    username="${1?username is required}" && shift
    token="${1?MFA token is required}" && shift
    profile="${1}" && [[ "$#" -gt 1 ]] && shift
    args=()
    if [[ -n "$profile" ]]; then
        args=(--profile "${profile}")
    fi
    eval "$(\
        aws sts \
            "${args[@]}" \
            get-session-token \
            --token-code "$token" \
            --serial-number "arn:aws:iam::934458803771:mfa/${username}" \
            | jq -r '.Credentials | "export AWS_ACCESS_KEY_ID=" + (.AccessKeyId) + "\nexport AWS_SECRET_ACCESS_KEY=" + (.SecretAccessKey) + "\nexport AWS_SESSION_TOKEN=" + (.SessionToken)'
   )"
}

# list all mounted volumes
docker-mounts() {
    if [[ -n $1 ]]; then
        containers=($(docker ps | awk "/$1/ { print \$1 }"))
    else
        containers=($(docker ps -q))
    fi
    docker inspect \
           -f '{{ .Name }}{{ range .Mounts }}{{ printf "\n\t" }}{{ .Type }} {{ if eq .Type "bind" }}{{ .Source }}{{ end }}{{ .Name }} => {{ .Destination }}{{ end }}' \
           "${containers[@]}" \
           ;
}

drun() {
    local usage="usage: drun IMAGE_NAME [COMMAND...]"
    if [[ $# -eq 0  ]]; then
        echo "$usage"
        return 1
    elif [[ "$*" =~ -h ]]; then
        echo -n "$usage

Run a docker image with the current directory mounted in the working dir
"
        return 0
    fi

    image_name=$1 && shift
    if [[ $# -gt 0 ]]; then
        command=("$@")
    else
        command=(bash)
    fi
    docker run -it --rm -v "$(pwd):/work" -w /work $image_name "${command[@]}"
}

dimgexec() {
    local usage="usage: dexec IMAGE_NAME [COMMAND...]"
    if [[ $# -eq 0  ]]; then
        echo "$usage"
        return 1
    elif [[ "$*" =~ -h ]]; then
        echo -n "$usage

Execute into a running docker container
"
        return 0
    fi

    image_name=$1 && shift
    if [[ $# -gt 0 ]]; then
        command=("$@")
    else
        command=(bash)
    fi

    container_id=$(docker ps | awk "/$image_name/ "'{ print $1 }')
    docker exec -it "$container_id" "${command[@]}"
}

function frg {
    result=$(
        rg --ignore-case --color=always --line-number --no-heading "$@" |
            fzf --ansi \
                --color 'hl:-1:underline,hl+:-1:underline:reverse' \
                --delimiter ':' \
                --preview "bat --color=always {1} --theme='Solarized (light)' --highlight-line {2}" \
                --preview-window 'up,60%,border-bottom,+{2}+3/3,~3'
    )
    file=${result%%:*}
    linenumber=$(echo "${result}" | cut -d: -f2)
    if [[ -n "$file" ]]; then
        $EDITOR +"${linenumber}" "$file"
    fi
}

alias jjab="jj ab"
alias jjj="JJUI=1 jjui"

alias gitab="git ab"
alias mdserve="mdserve --standalone --open"

# miniserve
ms() {
  # Figure out the port (miniserve defaults to 8080) so we can open the
  # browser without having to capture and parse miniserve's output.
  local port=8080 i
  for (( i = 1; i <= $#; i++ )); do
    case ${@[i]} in
      -p|--port) port=${@[i+1]} ;;
      -p=*|--port=*) port=${${@[i]}#*=} ;;
    esac
  done

  local opener
  if which open > /dev/null 2>&1; then
    opener=open
  elif which xdg-open > /dev/null 2>&1; then
    opener=xdg-open
  fi

  # Poll until the port accepts connections, then open the browser.
  # Backgrounded and disowned so it doesn't disturb miniserve on the terminal.
  if [[ -n $opener ]]; then
    (
      zmodload zsh/net/tcp
      local tries=0
      while ! ztcp localhost $port 2>/dev/null; do
        sleep 0.1
        (( ++tries > 100 )) && return   # give up after ~10s
      done
      ztcp -c 2>/dev/null
      $opener "http://localhost:$port"
    ) &!
  fi

  # Run miniserve in the foreground so it keeps the TTY: raw, colored output
  # and a working Ctrl-C.
  miniserve "$@"
}

# Vterm stuff, tells emacs which directory we're currently in
vterm_printf() {
    if [ -n "$TMUX" ]; then
        # Tell tmux to pass the escape sequences through
        # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}

if lesspipe=$(which lesspipe.sh 2>/dev/null) ; then
    export LESSOPEN="|'$lesspipe' %s" LESS_ADVANCED_PREPROCESSOR=1
fi

# anything that should be set only on this computer
[[ -f $HOME/.zshrc-local ]] && source "$HOME/.zshrc-local"
[[ -f "$HOME/.local/env" ]] && source "$HOME/.local/env"
