#!/usr/bin/env bash

set -euo pipefail

if ! which brew >/dev/null 2>&1; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

brew install \
    angle-grinder \
    bat \
    btop \
    coreutils \
    dust \
    eza \
    fd \
    fzf \
    git \
    git-absorb \
    git-delete-merged-branches \
    git-delta \
    jq \
    lazygit \
    lesspipe \
    mise \
    nvim \
    quodlibetor/git-tools/git-instafix \
    ripgrep \
    shellcheck \
    shfmt \
    starship \
    subversion \
    tmux \
    tokei \
    zoxide \
    zsh \
    ;

# to upgrade wezterm:
# brew upgrade --cask wezterm-nightly --no-quarantine --greedy-latest
brew tap homebrew/cask-versions # needed for wezterm

brew install --cask \
  rectangle \
  wezterm-nightly \
  ;

mkdir -p ~/.tmux/plugins
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

# options are https://github.com/railwaycat/homebrew-emacsmacport/blob/master/Formula/emacs-mac.rb
brew tap railwaycat/emacsmacport
#--enable-mac-app \
brew install emacs-mac --HEAD \
    --with-dbus \
    --with-imagemagick \
    --with-librsvg \
    --with-mac-metal \
    --with-native-comp \
    --with-no-title-bars \
    --with-starter \
    --with-xwidgets \
    ;

osascript -e 'tell application "Finder" to make alias file to POSIX file "/opt/homebrew/opt/emacs-mac/Emacs.app" at POSIX file "/Applications"'
