#!/usr/bin/env zsh

brew install \
    asdf \
    coreutils \
    exa \
    fzf \
    git \
    nvim \
    starship \
    shellcheck \
    subversion \
    tmux \
    zsh \
    ;

brew install --cask \
    rectangle \
    ;

mkdir -p ~/.tmux/plugins
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

brew install emacs-mac --HEAD \
   --enable-mac-app \
   --with-dbus \
   --with-imagemagick \
   --with-librsvg \
   --with-mac-metal \
   --with-native-comp \
   --with-no-title-bars \
   --with-starter \
   --with-xwidgets \
   ;
