" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

set nocompatible

syntax on

set background=dark
colorscheme onedark

" jump to the last edited line of a file when reopening
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" have Vim load indentation rules and plugins
filetype on
filetype plugin indent on

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set smartcase		" Do smart case matching
set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
set hidden		" Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)

set shiftwidth=4 " Set shift width to 4 spaces.
set tabstop=4 " Set tab width to 4 columns.
set expandtab " Use space characters instead of tabs.
set scrolloff=10 " Do not let cursor scroll below or above N number of lines when scrolling.
" set nowrap " Do not wrap lines. Allow long lines to extend as far as the line goes.
set showmode " Show the mode you are on the last line.
set hlsearch " Use highlighting when doing a search.
set history=1000 " Set the commands to save in history default number is 20.

set relativenumber
set number
set cursorline " highlight the line the cursor is on

set wildmenu " Enable auto completion menu after pressing TAB.
set wildmode=list:longest " Make wildmenu behave like similar to Bash completion.
